# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.CharField(max_length=200)),
                ('news_header', models.CharField(max_length=1000)),
                ('news_date_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
